#!/bin/bash

function buildCoffeescript {
  coffee --compile --output build/js coffee &
}

function buildGrunt {
  grunt build &
}

function startServer {
  grunt connect &
}

function watchCoffeescript {
  coffee --watch --compile --output build/js coffee &
}

function watchGrunt {
  grunt watch &
}

while [ "$1" != "" ]; do
  case $1 in
    --build | -b )  buildCoffeescript
                    buildGrunt
                    ;;
    --watch | -w )  watchCoffeescript
                    watchGrunt
                    ;;
    --run | -r )    watchCoffeescript
                    watchGrunt
                    startServer
                    ;;
  esac
  shift
done